<?php
	$toolTips = array();

	$toolTips["missili1"] = "Missili live 1 - Spara un singolo missile che insegue un bersaglio fino all'impatto. Nel caso il bersaglio venga distrutto prima, cerca un nuovo bersaglio. Se non ci sono più bersagli disponibili, si autodistrugge. Non possono bersagliare proiettili nemici o nemici già bersagliati da altri missili. Cooldown per armi speciali: 1.6 secondi";
	$toolTips["missili2"] = "Missili livello 2 - Spara fino a 3 missili, a seconda dei bersagli disponibili, che inseguono un bersaglio fino all'impatto. Nel caso il bersaglio venga distrutto prima, il missile che lo inseguiva cerca un nuovo bersaglio. Se non ci sono più bersagli disponibili, si autodistrugge. Non possono bersagliare proiettili nemici o nemici già bersagliati da altri missili. Cooldown per armi speciali: 3.2 secondi per ogni missile lanciato";
	$toolTips["missili3"] = "Missili livello 3 - Spara fino a 7 missili, a seconda dei bersagli disponibili, che inseguono un bersaglio fino all'impatto. Nel caso il bersaglio venga distrutto prima, il missile che lo inseguiva cerca un nuovo bersaglio. Se non ci sono più bersagli disponibili, si autodistrugge. Non possono bersagliare proiettili nemici o nemici già bersagliati da altri missili. Cooldown per armi speciali: 4.8 secondi per ogni missile lanciato";

	$toolTips["bomba1"] = "Bomba livello 1 - I proiettili sparati presenti nel campo esplodono, generando 4 schegge ciascuno che si allontanano lungo le 4 direzioni ortogonali. Quest'arma impedisce di usare anche il fuoco standard, per metà del cooldown per armi speciali. Le schegge derivate dalle esplosioni, come anche missili a ricerca, non possono esplodere. Cooldown per armi speciali: 2 secondi. Cooldown per fuoco standard: 1 secondo";
	$toolTips["bomba2"] = "Bomba livello 2 - I proiettili sparati presenti nel campo esplodono, generando 8 schegge ciascuno che si allontanano lungo le 4 direzioni ortogonali e le 4 diagonali. Quest'arma impedisce di usare anche il fuoco standard, per metà del cooldown per armi speciali. Le schegge derivate dalle esplosioni, come anche missili a ricerca, non possono esplodere. Cooldown per armi speciali: 8 secondi. Cooldown per fuoco standard: 4 secondi";
	$toolTips["bomba3"] = "Bomba livello 3 - I proiettili sparati presenti nel campo esplodono, generando 4 nuovi proiettili ciascuno che si allontanano lungo le 4 direzioni ortogonali. Dopo 0.5 secondi i proiettili generati da questa prima esplosione esplodono a loro volta secondo le modalita' di una bomba livello 2. Quest'arma impedisce di usare anche il fuoco standard, per metà del cooldown per armi speciali. Le schegge derivate dalle esplosioni di livello 1 e 2, come anche missili a ricerca, non possono esplodere. Cooldown per armi speciali: 18 secondi. Cooldown per fuoco standard: 9 secondi";

	$toolTips["scudo1"] = "Scudo livello 1 - Si attiva una barriera protettiva attorno all'aereo che dura 2 secondi, durante i quali ogni collisione con nemici porterà alla distruzione dei nemici lasciando illeso l'aereo. Cooldown per armi speciali: 3 secondi";
	$toolTips["scudo2"] = "Scudo livello 1 - Si attiva una barriera protettiva attorno all'aereo che dura 4 secondi, durante i quali ogni collisione con nemici porterà alla distruzione dei nemici lasciando illeso l'aereo. Cooldown per armi speciali: 6 secondi";
	$toolTips["scudo3"] = "Scudo livello 1 - Si attiva una barriera protettiva attorno all'aereo che dura 6 secondi, durante i quali ogni collisione con nemici porterà alla distruzione dei nemici lasciando illeso l'aereo. Cooldown per armi speciali: 9 secondi";
	
	$toolTips["standard1"] = "Standard - Aereo di base, velocità di movimento e rateo di fuoco nella norma. Spara un colpo alla volta, in direzione verticale";
	$toolTips["speeder1"] = "Speeder - Aereo dall'alta velocità di movimento, controbilanciata però da un lento rateo di fuoco. Spara un colpo alla volta, in direzione verticale";
	$toolTips["doubleshot1"] = "DobleShot - Aereo dalla ridotta capacità di movimento ma dall'alto rateo di fuoco. Spara due colpi alla volta, in direzione verticale";
	$toolTips["xevious1"] = "Xevious - Molto difficile da manovrare, quest'aereo ha la stessa velocità di movimento del DoubleShot ma spara ben 4 colpi a ventaglio - la sfida sta nel dover rimanere fermi per poter sparare";
?>